/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xhI0F35wkLb
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import Image from "next/image"
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel"
import Icon from "@/components/ui/icon"
import logo from "@/public/mic.png"

// import { MainNav } from "./main-nav"

export default function HomePage() {
  return (
    <div className="max-w-7xl mx-auto">
      {/* <nav className="flex justify-between">
        <div className="flex flex-row space-x-4">
          <Image
            alt="Mic Logo"
            height={100}
            src={logo}
            width={100}
            // className="w-auto h-auto"
          />

          <div className="flex space-x-4 items-center">
            <Link className="text-lg font-semibold" href="/">
              Home
            </Link>
            <Link className="text-lg font-semibold" href="/specials">
              Specials
            </Link>
            <Link className="text-lg font-semibold" href="#">
              Comedians
            </Link>
          </div>
        </div>
        <div className="w-1/4 my-auto">
          <Input placeholder="Search" type="search" />
        </div>
      </nav> */}
      <section className="my-6 px-4">
        <h2 className="text-2xl font-bold mb-4">Featured</h2>
        <div className="rounded overflow-hidden mb-6 flex justify-center items-center flex-col">
          <Link href="/specials/shane-gillis-live-in-austin">
            <Image
              alt="Shane Gillis Live in Austin"
              className="w-auto h-auto rounded-xl overflow-hidden"
              height="720"
              src="/liveinaustin.jpg"
              width="1280"
              quality={100}
              style={
                {
                  // aspectRatio: "1280/720",
                  // objectFit: "cover",
                }
              }
            />
            {/* <div className="mt-4">
            <p className="text-center">
              Image description or any text you want to place under the image
            </p>
          </div> */}
            <div className="flex flex-col justify-center items-center p-4">
              <p className="text-3xl font-bold">Shane Gillis</p>
              <p className="text-lg">Live in Austin</p>
            </div>
          </Link>
          {/* <div className=" flex flex-col justify-center items-center p-4 bg-white bg-opacity-50 rounded-xl">
            <p className="text-3xl font-bold">Shane Gillis</p>
            <p className="text-lg">Live in Austin</p>
          </div> */}
        </div>
      </section>
      <section className="my-6 px-4">
        <h2 className="text-2xl font-bold mb-4">Most Popular</h2>

        <Carousel>
          <CarouselContent>
            <CarouselItem className="basis-1/3">
              <Link href="/specials/hat-trick">
                <Image
                  alt="Fahim Anwar Hat Trick"
                  className="w-full rounded overflow-hidden"
                  height={720}
                  src="/hattrick.jpg"
                  style={{
                    // aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width={1280}
                />
                <div className="p-4">
                  <p className="text-lg font-semibold">Fahim Anwar</p>
                  <p className="text-sm">Hat Trick</p>
                </div>
              </Link>
            </CarouselItem>
            <CarouselItem className="basis-1/3">
              <div className="rounded overflow-hidden">
                <Image
                  alt="Mark Normand Out to Lunch"
                  className="w-full rounded overflow-hidden"
                  height={720}
                  src="/outtolunch.jpg"
                  style={{
                    // aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width={1280}
                />
                <div className="p-4">
                  <p className="text-lg font-semibold">Mark Normand</p>
                  <p className="text-sm">Out to Lunch</p>
                </div>
              </div>
            </CarouselItem>
            <CarouselItem className="basis-1/3">
              <div className="rounded overflow-hidden">
                <Link href="/specials/shane-gillis-live-in-austin">
                  <Image
                    alt="Shane Gillis Live in Austin"
                    className="w-full rounded overflow-hidden"
                    height={720}
                    src="/liveinaustin.jpg"
                    style={{
                      // aspectRatio: "300/200",
                      objectFit: "cover",
                    }}
                    width={1280}
                  />
                  <div className="p-4">
                    <p className="text-lg font-semibold">Shane Gillis</p>
                    <p className="text-base">Live in Austin</p>
                  </div>
                </Link>
              </div>
            </CarouselItem>
            <CarouselItem className="basis-1/3">
              <div className="rounded overflow-hidden">
                <Image
                  alt="Stavros Halkias Live at the Lodge Room"
                  className="w-full rounded overflow-hidden"
                  height={720}
                  src="/liveatthelodgeroom.jpg"
                  style={{
                    // aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width={1280}
                />
                <div className="p-4">
                  <p className="text-lg font-semibold">Stavros Halkias</p>
                  <p className="text-base">Live at the Lodge Room</p>
                </div>
              </div>
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious className="text-white" />
          <CarouselNext className="text-white" />
        </Carousel>
        {/* <div className="grid grid-cols-3 gap-4">
          <div className="rounded overflow-hidden">
            <Link href="/specials/hat-trick">
              <Image
                alt="Fahim Anwar Hat Trick"
                className="w-full rounded overflow-hidden"
                height={720}
                src="/hattrick.jpg"
                style={{
                  // aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width={1280}
              />
              <div className="p-4">
                <p className="text-lg font-semibold">Fahim Anwar</p>
                <p className="text-sm">Hat Trick</p>
              </div>
            </Link>
          </div>
          <div className="rounded overflow-hidden">
            <Image
              alt="Mark Normand Out to Lunch"
              className="w-full rounded overflow-hidden"
              height={720}
              src="/outtolunch.jpg"
              style={{
                // aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width={1280}
            />
            <div className="p-4">
              <p className="text-lg font-semibold">Mark Normand</p>
              <p className="text-sm">Out to Lunch</p>
            </div>
          </div>
          <div className="rounded overflow-hidden">
            <Link href="/specials/shane-gillis-live-in-austin">
              <Image
                alt="Shane Gillis Live in Austin"
                className="w-full rounded overflow-hidden"
                height={720}
                src="/liveinaustin.jpg"
                style={{
                  // aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width={1280}
              />
              <div className="p-4">
                <p className="text-lg font-semibold">Shane Gillis</p>
                <p className="text-base">Live in Austin</p>
              </div>
            </Link>
          </div>
        </div> */}
      </section>
      <section className="my-6 px-4">
        <h2 className="text-2xl font-bold mb-4">Recent</h2>
        <div className="grid grid-cols-3 gap-4">
          <div className="rounded overflow-hidden">
            <Image
              alt="Stavros Halkias Live at the Lodge Room"
              className="w-full rounded overflow-hidden"
              height={720}
              src="/liveatthelodgeroom.jpg"
              style={{
                // aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width={1280}
            />
            <div className="p-4">
              <p className="text-lg font-semibold">Stavros Halkias</p>
              <p className="text-base">Live at the Lodge Room</p>
            </div>
          </div>
          <div className="rounded overflow-hidden">
            <Image
              alt="Bill Burr Live at Red Rocks"
              className="w-full rounded overflow-hidden"
              height={1145}
              src="/liveatredrocks.png"
              style={{
                // aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width={2044}
              // fill
            />
            <div className="p-4">
              <p className="text-lg font-semibold">Bill Burr</p>
              <p className="text-base">Live at Red Rocks</p>
            </div>
          </div>
          <div className="rounded overflow-hidden">
            <Image
              alt="Joe List This Year's Material"
              className="w-full rounded overflow-hidden"
              height={720}
              src="/thisyearsmaterial.jpg"
              style={{
                // aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width={1280}
              quality={100}
            />
            <div className="p-4">
              <p className="text-lg font-semibold">Joe List</p>
              <p className="text-base">This Year&apos;s Material</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
