/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dHZZt09pQko
 */
import { Input } from "@/components/ui/input"
import { CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Image from "next/image"
import Link from "next/link"
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

export async function Specials() {
  const specials = await prisma.specials.findMany()
  return (
    <div className="max-w-7xl mx-auto">
      {/* <nav className="flex justify-between p-4">
        <div className="flex space-x-4">
          <Link className="text-lg font-semibold" href="/">
            Home
          </Link>
          <Link className="text-lg font-semibold" href="/specials">
            Specials
          </Link>
          <Link className="text-lg font-semibold" href="#">
            Comedians
          </Link>
        </div>
        <div className="w-1/4">
          <Input placeholder="Search" type="search" />
        </div>
      </nav> */}
      <h2 className="text-2xl font-bold justify-start items-start max-w-7xl mx-auto p-4">
        Specials
      </h2>
      <div className="flex flex-col justify-center items-center">
        <div className="max-w-7xl p-4 space-y-6">
          <div
            className="
          grid
          grid-cols-1
          md:grid-cols-2
          lg:grid-cols-3
          gap-4"
          >
            {specials.map((special, idx) => {
              return (
                <div key={idx} className="space-y-4">
                  <Link
                    href={`
                /specials/${special.title.toLowerCase().replace(/\s/g, "-")}
                `}
                  >
                    <Card className="w-full overflow-hidden">
                      <Image
                        alt={special.title}
                        className="w-full h-auto overflow-hidden object-cover"
                        height={720}
                        src={special.image || ""}
                        style={{
                          aspectRatio: "350/200",
                          objectFit: "cover",
                        }}
                        width={1280}
                      />
                      <CardContent className="mt-2">
                        <h3 className="text-lg font-semibold">
                          {special.title}
                        </h3>
                        <p className="text-sm text-gray-600">
                          {special.comedian}
                        </p>
                      </CardContent>
                    </Card>
                  </Link>
                </div>
              )
            })}
          </div>

          {/* <Link href="https://www.youtube.com/watch?v=HaTA-HVCo4w">
              <Card className="w-full overflow-hidden">
                <Image
                  alt="Hat Trick - Fahim Anwar"
                  className="w-full h-auto"
                  height={720}
                  src="/hattrick.jpg"
                  style={{
                    aspectRatio: "350/200",
                    objectFit: "cover",
                  }}
                  width={1280}
                />
                <CardContent className="mt-2">
                  <h3 className="text-lg font-semibold">Hat Trick</h3>
                  <p className="text-sm text-gray-600">Fahim Anwar</p>
                </CardContent>
              </Card>
            </Link>
            <Card className="w-full overflow-hidden">
              <Image
                alt="Jerrod Carmichael"
                className="w-full h-auto"
                height={720}
                src="/rothaniel.jpg"
                style={{
                  aspectRatio: "350/200",
                  objectFit: "cover",
                }}
                width={1280}
              />
              <CardContent className="mt-2">
                <h3 className="text-lg font-semibold">Rothaniel</h3>
                <p className="text-sm text-gray-600">Jerrod Carmichael</p>
              </CardContent>
            </Card>
            <Card className="w-full overflow-hidden">
              <Image
                alt="Chris Distefano"
                className="w-full h-auto"
                height={720}
                src="/speshyweshy.jpg"
                style={{
                  aspectRatio: "350/200",
                  objectFit: "cover",
                }}
                width={1280}
              />
              <CardContent className="mt-2">
                <h3 className="text-lg font-semibold">Speshy Weshy</h3>
                <p className="text-sm text-gray-600">Chris Distefano</p>
              </CardContent>
            </Card>
            <Card className="w-full overflow-hidden">
              <Image
                alt="Rosebud Baker"
                className="w-full h-auto"
                height={720}
                src="/whiskeyfists.jpg"
                style={{
                  aspectRatio: "350/200",
                  objectFit: "cover",
                }}
                width={1280}
              />
              <CardContent className="mt-2">
                <h3 className="text-lg font-semibold">Whiskey Fists</h3>
                <p className="text-sm text-gray-600">Rosebud Baker</p>
              </CardContent>
            </Card>
            <Card className="w-full overflow-hidden">
              <Image
                alt="Joe List"
                className="w-full h-auto"
                height={720}
                src="/enoughforeverybody.jpg"
                style={{
                  aspectRatio: "350/200",
                  objectFit: "cover",
                }}
                width={1280}
              />
              <CardContent className="mt-2">
                <h3 className="text-lg font-semibold">Enough For Everybody</h3>
                <p className="text-sm text-gray-600">Joe List</p>
              </CardContent>
            </Card> */}
          {/* </div> */}
        </div>
        {/* <section className="md:w-1/2 p-4 mt-14 space-y-[310px]">
          <Link
            href={`
                /specials/${special.title.toLowerCase().replace(/\s/g, "-")}
                `}
          >
            <article>
              <h2 className="text-2xl font-bold">Hat Trick - Fahim Anwar</h2>
              <ul className="mt-4 space-y-1 text-sm">
                <li>
                  <strong>Written & Performed By: </strong>
                  Fahim Anwar{"\n"}
                </li>
                <li>
                  <strong>Directed By: </strong>
                  Fahim Anwar{"\n"}
                </li>
                <li>
                  <strong>Edited & Colored By: </strong>
                  Jeremy Johnstone{"\n"}
                </li>
                <li>
                  <strong>Music: </strong>
                  Allen Blickle & Josh Wiener{"\n"}
                </li>
              </ul>
            </article>
          </Link>
          <article className="">
            <h2 className="text-2xl font-bold">
              Jerrod Carmichael - Rothaniel
            </h2>
            <ul className="mt-4 space-y-1 text-sm">
              <li>
                <strong>Written & Performed By: </strong>
                Jerrod Carmichael{"\n"}
              </li>
              <li>
                <strong>Directed By: </strong>
                Jerrod Carmichael{"\n"}
              </li>
              <li>
                <strong>Edited & Colored By: </strong>
                Jerrod Carmichael{"\n"}
              </li>
              <li>
                <strong>Music: </strong>
                Jerrod Carmichael{"\n"}
              </li>
            </ul>
          </article>
          <article className="">
            <h2 className="text-2xl font-bold">
              Chris Distefano - Speshy Weshy
            </h2>
            <ul className="mt-4 space-y-1 text-sm">
              <li>
                <strong>Written & Performed By: </strong>
                Chris Distefano{"\n"}
              </li>
              <li>
                <strong>Directed By: </strong>
                Chris Distefano{"\n"}
              </li>
              <li>
                <strong>Edited & Colored By: </strong>
                Chris Distefano{"\n"}
              </li>
              <li>
                <strong>Music: </strong>
                Chris Distefano{"\n"}
              </li>
            </ul>
          </article>
          <article className="">
            <h2 className="text-2xl font-bold">
              Rosebud Baker - Whiskey Fists
            </h2>
            <ul className="mt-4 space-y-1 text-sm">
              <li>
                <strong>Written & Performed By: </strong>
                Rosebud Baker{"\n"}
              </li>
              <li>
                <strong>Directed By: </strong>
                Rosebud Baker{"\n"}
              </li>
              <li>
                <strong>Edited & Colored By: </strong>
                Rosebud Baker{"\n"}
              </li>
              <li>
                <strong>Music: </strong>
                Rosebud Baker{"\n"}
              </li>
            </ul>
          </article>
          <article className="">
            <h2 className="text-2xl font-bold">
              Joe List - Enough For Everybody
            </h2>
            <ul className="mt-4 space-y-1 text-sm">
              <li>
                <strong>Written & Performed By: </strong>
                Joe List{"\n"}
              </li>
              <li>
                <strong>Directed By: </strong>
                Joe List{"\n"}
              </li>
              <li>
                <strong>Edited & Colored By: </strong>
                Joe List{"\n"}
              </li>
              <li>
                <strong>Music: </strong>
                Joe List{"\n"}
              </li>
            </ul>
          </article>
        </section> */}
      </div>
    </div>
  )
}
